name: AZPlugin
version: '${project.version}'
main: fr.mathip.azplugin.Main
author: MATHIP6
commands:
  az:
    description: commande du plugin.
    permission: azplugin.commands
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande !

permissions:
  azplugin.command.size:
    description: Permission pour la commande principale
    default: op
  azplugin.command.check:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.list:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.reload:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.itemrender:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.model:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.opacity:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.tag:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.suptag:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.subtag:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.worldenv:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.vignette:
    description: Permission pour la sous-commande 1
    default: op
  azplugin.command.seechunks:
    description: Permission pour la sous-commande 1
    default: op

